language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database app_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - npm install

script:
  - ./vendor/bin/phpunit
  - npm run production

cache:
  directories:
    - node_modules
    - vendor

branches:
  only:
    - develop