language: php

php:
  - 7.1

env:
  - DB_DATABASE=app DB_USERNAME=app DB_PASSWORD=secret

install:
  - echo $DB_DATABASE
  - composer self-update
  - travis_retry composer install --no-interaction

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - mysql -e 'create database app;'
  - php artisan key:generate
  - php artisan migrate
  - npm install

script:
  - ./vendor/bin/phpunit
  - npm run production

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

branches:
  only:
    - develop