sudo: required
language: php

php:
  - 7.1

env:
  - DB_DATABASE=app DB_USERNAME=app DB_PASSWORD=secret

install:
  - echo $DB_DATABASE
  - echo $DB_USERNAME
  - echo $DB_PASSWORD
  - composer self-update
  - travis_retry composer install --no-interaction
  - mysql -e "create user '$DB_USERNAME'@'localhost' identified by '$DB_PASSWORD';"
  - mysql -e "grant all privileges on *.* to '$DB_USERNAME'@'localhost' with grant option;"
  - mysql -u$DB_USERNAME -p$DB_PASSWORD -e "create database app;"

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  - npm install

script:
  - ./vendor/bin/phpunit
  - npm run production

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

branches:
  only:
    - develop