sudo: required
language: php
dist: trusty

php:
  - 7.1

env:
  - DB_DATABASE=app DB_USERNAME=app DB_PASSWORD=secret

install:
  - echo $DB_DATABASE
  - composer self-update
  - travis_retry composer install --no-interaction
  - mysql -e "create user '$DB_USERNAME'@'localhost' identified by '$DB_PASSWORD';"
  - mysql -e "grant all privileges on *.* to '$DB_USERNAME'@'localhost' with grant option;"
  - mysql -u$DB_USERNAME -p$DB_PASSWORD -e "create database $DB_DATABASE;"

before_script:
  - cp .env.travis .env
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php artisan key:generate
  - php artisan migrate
  - npm install
  -
before_install:
  - mysql -e 'CREATE DATABASE app;'

script:
  - ./vendor/bin/phpunit
  - npm run production

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

branches:
  only:
    - develop